server:
  port: 8088

spring:
  profiles:
    active: dev
framework:
  security:
    # 是否开启 spring security
    switch: false
    white-list: /a, /b, /websocket/*
  config:
    redis:
      enable: true
    dubbo:
      enable: true
    mongo:
      enable: true
    swagger:
      enable: true
      scan-package: com.magic.platform
